apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  labels:
    component: nvidia-gpu
spec:
  containers:
    - name: gpu-container
      image: mirrorgcrio/pause:2.0
  nodeSelector:
    component: nvidia-gpu