apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.component: dedicated-toleration-webhook
  app: dedicated-toleration-webhook
namePrefix: dedicated-toleration-webhook-
resources:
  - deployment.yaml
  - service.yaml
  - mutating-webhook-configuration.yaml